version: '3.9'

networks:
  monitoring:
  docker_default:
    external: true

services:
  ttn-connector:
    image: aaronschweig/twinevent-ttn
    volumes:
      - ./.default-config.yaml:/config.yaml:ro
    networks:
      - monitoring
      - docker_default

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 3000:3000
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
    #   - GF_USERS_ALLOW_SIGN_UP=false
    #   - GF_SERVER_DOMAIN=myrul.com
    #   - GF_SMTP_ENABLED=true
    #   - GF_SMTP_HOST=smtp.gmail.com:587
    #   - GF_SMTP_USER=myadrress@gmail.com
    #   - GF_SMTP_PASSWORD=mypassword
    #   - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
